[workspace]
resolver = "2"
members = [
  "sqlshield",
  "sqlshield-cli",
  "sqlshield-py",
]

[workspace.package]
version = "0.0.1"
authors = ["David Freire <davidsmfreire@gmail.com>"]
edition = "2021"

[workspace.dependencies]
sqlshield = { version = "0.0.1", path = "sqlshield"}
