import { Button, VerticalBox, HorizontalBox, TextEdit, StandardListView } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 1000px;
    height: 700px;

    in-out property<string> queries: "";
    in-out property<string> schema: "";
    in property<[StandardListViewItem]> errors: [];
    callback request-text-edited(string, string);
    VerticalBox {
        HorizontalBox {
            width: 1000px;
            height: 500px;
            VerticalBox {
                Text {
                    text: "Queries";
                }
                TextEdit {
                    text: queries;
                    edited(text) => {
                        root.request-text-edited(text, "queries");
                    }
                }
            }
            VerticalBox {
                Text {
                    text: "Schema";
                }
                TextEdit {
                    text: schema;
                    edited(text) => {
                        root.request-text-edited(text, "schema");
                    }
                }
            }
        }
        HorizontalBox {
            Text {
                text: "Errors";
            }
            StandardListView {
                height: 200px;
                model: errors;
            }
        }
    }
}
